---

#spring.datasource.hikari.data-source-properties.useSSL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: demo
    password: demo
#    url: jdbc:mysql://localhost:3306/demo?useSSL=false&useTimezone=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    url: jdbc:mysql://localhost:3306/demo_dev
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        useSSL: false
        useTimezone: true
        serverTimezone: UTC
        useLegacyDatetimeCode: false
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
    enabled: true
    locations: filesystem:databases/migrations
server:
  port: 8090
demo:
  baseUrl: http://localhost:8090