platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8-jdk'

inputs:
  - name: main-git
  - name: ci-git

caches:
  - path: .gradle/

output:
  - name: deploy

run:
  path: ci-git/ci/demo/build.sh
  args:
    - main-git